server:
  port: 9008

management:
 server.port: 19008
 context-path: /mgr # /mgr/actuator 查看监控信息列表
 endpoints:
     # 暴露 EndPoint 以供访问，有jmx和web两种方式，exclude 的优先级高于 include
     jmx:
       exposure:
         include: '*'
     web:
       exposure:
       # exclude: '*'
         include: ["health","info","beans","mappings","logfile","metrics","shutdown","env"]
       base-path: /actuator  # 配置 Endpoint 的基础路径
       cors: # 配置跨域资源共享
         allowed-origins: http://example.com
         allowed-methods: GET,POST
     enabled-by-default: true # 修改全局 endpoint 默认设置
 endpoint:
     auditevents: # 1、显示当前引用程序的审计事件信息，默认开启
       enabled: true
       cache:
         time-to-live: 10s # 配置端点缓存响应的时间
     beans: # 2、显示一个应用中所有 Spring Beans 的完整列表，默认开启
       enabled: true
     conditions: # 3、显示配置类和自动配置类的状态及它们被应用和未被应用的原因，默认开启
       enabled: true
     configprops: # 4、显示一个所有@ConfigurationProperties的集合列表，默认开启
       enabled: true
     env: # 5、显示来自Spring的 ConfigurableEnvironment的属性，默认开启
       enabled: true
     flyway: # 6、显示数据库迁移路径，如果有的话，默认开启
       enabled: true
     health: # 7、显示健康信息，默认开启
       enabled: true
       show-details: always
     info: # 8、显示任意的应用信息，默认开启
       enabled: true
     liquibase: # 9、展示任何Liquibase数据库迁移路径，如果有的话，默认开启
       enabled: true
     metrics: # 10、展示当前应用的metrics信息，默认开启
       enabled: true
     mappings: # 11、显示一个所有@RequestMapping路径的集合列表，默认开启
       enabled: true
     scheduledtasks: # 12、显示应用程序中的计划任务，默认开启
       enabled: true
     sessions: # 13、允许从Spring会话支持的会话存储中检索和删除(retrieval and deletion)用户会话。使用Spring Session对反应性Web应用程序的支持时不可用。默认开启。
       enabled: true
     shutdown: # 14、允许应用以优雅的方式关闭，默认关闭
       enabled: true
     threaddump: # 15、执行一个线程dump
       enabled: true
     # web 应用时可以使用以下端点
     heapdump: # 16、    返回一个GZip压缩的hprof堆dump文件，默认开启
       enabled: true
     jolokia: # 17、通过HTTP暴露JMX beans（当Jolokia在类路径上时，WebFlux不可用），默认开启
       enabled: true
     logfile: # 18、返回日志文件内容（如果设置了logging.file或logging.path属性的话），支持使用HTTP Range头接收日志文件内容的部分信息，默认开启
       enabled: true
     prometheus: #19、以可以被Prometheus服务器抓取的格式显示metrics信息，默认开启
       enabled: true

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #目前有两个容器实例，单个请求超时3s,+重试>3s，超6s则熔断
          timeoutInMilliseconds: 6000

ribbon:
  #ribbon请求连接的超时时间- 限制3秒内必须请求到服务，并不限制服务处理的返回时间
  connectTimeout: 3000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout,超时时间不可大于断路器的超时时间
  readTimeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6761/eureka

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:mapper/*Mappexml
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lind.bookshop.entity
  lazyLoadingEnabled: true #开启延时加载
  aggressiveLazyLoading: false #只有当访问扩展属性时才加载它
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局 唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: user_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  typeHandlersPackage: com.lind.bookshop.Interceptor
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
spring:
  cloud.refresh.enabled: false #避免mybatis里的循环引用
  application:
      name: bookshop
  profiles:
      active: dev
  thymeleaf:
        prefix: classpath:/templates/ #注意页面和action指向路径开头不要加/
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
        servlet:
          multipart:
             max-file-size: 2MB
        resources:
            static-locations: classpath:static/,file:static/


---
spring:
  profiles: dev
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/bookshop?useSSL=false&characterEncoding=utf8&useSSL=false
     username: root
     password: Abc123##

---
spring:
  profiles: test
  h2:
      console:
        enabled: true
        path: /h2
  datasource:
      url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      driver-class-name: org.h2.Driver
      schema: classpath:db/*.sql
      initialization-mode: always
      platform: h2